### ISSUE TITLE
UIButton always showing box-shadow highlighted state

### ISSUE THREAD

**Issue by iamjohnford** [Pixate/pixate-freestyle-ios#104]
I've run into a case where it appears that the highlighted state is always active when using box-shadow. It also seems to be setting the box-shadow on the button label depending on the button type and state. I've noticed the example below changes depending on the button type but in my app I've extended UIButton for some additional customization. Do I need to set some other button properties to make this work? 

Here's an example where you can see the red from the highlighted state always showing.

``` css
button {
    color: white;
    background-color: black;
    box-shadow: 0px 1px 1px 0px lightgray;
}

button:highlighted {
    color: white;
    background-color: darkgray;
    box-shadow: 0px 1px 1px 0px red;
}
```

Thanks!
