### ISSUE TITLE
Doesn't acknowledge CSS @media orientation on initial load

### ISSUE THREAD

**Issue by Bodacious** [Pixate/pixate-freestyle-ios#108]
I'm using Pixate Freestyle in a Rubymotion iPad app I'm developing

I have the following CSS in my default.css file:

``` css
#titleLabel {
  top: 260px;
  left: 234px;
  width: 300px;
  height: 60px;

  font-size: 60px;
  color: #333333;
  text-align: center; 
}
@media (orientation: landscape) {
  #titleLabel {
    left: 362px; 
  }
}
```

When the app is booted in landscape orientation, the left position value of #titleLabel is 234px (the value defined for portrait orientation). After turning the iPad round a couple of times, the landscape positioning works as expected.

I've tried this in an isolated app to make sure it wasn't just my implementation in this one.
