### ISSUE TITLE
Add/Remove CSS classes

### ISSUE THREAD

**Issue by nuthinking** [Pixate/pixate-freestyle-ios#118]
In the project I am currently working on I am taking advantage of the descendant selector to change the look of more elements adding a class to the parent container.

``` css
.calendar-list-header label
{
    font-family: "Avenir-Light";
    font-size: 15pt;
    color: white;
}

.calendar-list-header.today label
{
    color: blue;
}

.calendar-list-header label.numeric
{
    font-family: "Avenir-Light";
    font-size: 20pt;
}
```

It works like a charm.

The Objective-C implementation though is not as clean as it could be (in a uicollection reusable view):

``` objective-c
- (void)setDay:(NSDate *)day
{
    if([day isToday]){
        self.styleClass = @"calendar-list-header today";
    }else{
        self.styleClass = @"calendar-list-header";
    }
    ....
}
```

What you usually do in JavaScript, through third party frameworks, you add or remove a class name.
In FreeStyle it could look like this:

``` objective-c
- (void)setDay:(NSDate *)day
{
    if([day isToday]){
        [self.addStyleClass: @"today"];
    }else{
        [self.removeStyleClass: @"today"];
    }
    ....
}
```

Assuming that such thing is not possible, I couldn't find in the API, I think this could be a useful feature.
