### ISSUE TITLE
UIImageView background-image size

### ISSUE THREAD

**Issue by nuthinking** [Pixate/pixate-freestyle-ios#121]
I am currently setting only the image background property from the catalogue:

``` css
.iconTest
{
    background-image: url(asset://starIcon);
}
```

When the image is set in the UIImageView, it seems to be 50x50 size despite the original asset has different size. Is it possible not to have to set the size via css and use for instance self.contentMode = UIViewContentModeCenter; in Cocoa? Thanks!
