### ISSUE TITLE
background-color not computed correctly

### ISSUE THREAD

**Issue by KptainO** [Pixate/pixate-freestyle-ios#122]
Hi,

Found a bug on Pixate backgrounds

Using this css

``` css
button:normal {
    background-color: blue;
    border-radius: 0;
}

button:selected {
    background-color: rgb(255, 122, 0);
    border-radius: 20px;
}
```

then both normal and selected background are showing up when button is selected.

Cheers,
