### ISSUE TITLE
[bug] border-radius on UIImageView with UIImage set via code not working

### ISSUE THREAD

**Issue by esttorhe** [Pixate/pixate-freestyle-ios#128]
Setting a class like this:

``` css
.profile-thumnbnail {
  border-radius: 6px;
}
```

And then assigning that to the `styleClass` of a `UIImageView` doesn't renders the corners as expected.

If i set something like this:

``` css
.profile-thumnbnail {
  border-radius: 6px;
  border: 1px solid #dddddd;
}
```

I can see the border being drawn correctly; rounded corners and everything but after I set the image via code the rendering disappears.
