### ISSUE TITLE
:pseudo class not take on tag class 

### ISSUE THREAD

**Issue by zhigang1992** [Pixate/pixate-freestyle-ios#134]
``` css
button {
  border-radius: 5pt;
}
button.active {
  background-color: #95a5a6;
}
button:highlighted {
  background-color: #95a5a0;
}
```

Now `button.active` takes on the button attribute `border-radius` like expected,
But not `button:highlighted`
