### ISSUE TITLE
button element: background-color:transparent is ignored

### ISSUE THREAD

**Issue by andreacremaschi** [Pixate/pixate-freestyle-ios#159]
Hi,
let's say there is a UIButton created in the IB with white background. 
This is being styled in SCSS with the following code:

``` scss
button.push:normal {
    color: $white;
    background-color: transparent;
    background-image: url(menu_button_green.png);
}
```

What happens is that the UIButton is styled with the correct image but the background image is still solid white. If I change the code above with this: 

``` scss
button.push:normal {
    color: $white;
    background-color: $red;
    background-image: url(menu_button_green.png);
}
```

The background color is correctly changed to red.
Freestyle seems to ignore the "background-color:transparent" attribute for buttons but not the "background-color:$red"
