### ISSUE TITLE
Can't access children of selected table-view-cells

### ISSUE THREAD

**Issue by pcolton** [Pixate/pixate-freestyle-ios#23]
I want to target the children of selected table-view-cells. I can't."

Example:

``` css
.MyTableViewCell:selected > label{
font-weight : bold;
}
```

Makes all labels bold.
