### ISSUE TITLE
UISwitch Text Disappears When Background Color Set

### ISSUE THREAD

**Issue by pcolton** [Pixate/pixate-freestyle-ios#26]
``` css
switch on{
background-color:#7CAEE0;
}
```

This was tested on iOS 6.1
