### ISSUE TITLE
Unable to set icon for UIButton selected state

### ISSUE THREAD

**Issue by pcolton** [Pixate/pixate-freestyle-ios#33]
The following CSS does not work:

``` css
#gpbutton:selected icon{  
    background-image: url(logo-gplus-white.png);  
    background-size: 20px;  
}  
#gpbutton:normal icon{  
    background-image: url(logo-gplus.png);  
    background-size: 20px;  
}
```

This is due to the fact that the framework processes pseudo-classes on the last element only. We need to make an exception for virtual children to allow this case to work properly.
