### ISSUE TITLE
Better structure by using viewController class names

### ISSUE THREAD

**Issue by pcolton** [Pixate/pixate-freestyle-ios#46]
(From user seivan)

I think Pixate and non-DOM design could do well by introducing some practices of their own that would find the native style software development (compared to say DOM and HTML).

One practice that I use here is to set the name of the class of each controller on its view `styleId` and the name of the super class as its `styleClass`.

That way I can have `@import 'includes/controllers/*';` in my `default.css.scss`.

The purpose is that you might have a viewController OR a set of viewControllers that might have different button design.

One sample is for instance our signup progress or our on boarding process. 
All signup views inherit from a signup super class.

That way I can do 

``` css
#XXXSignUpSuperViewController {
   .button {  
      border-radius: inherit; 
    }
}
```
