### ISSUE TITLE
Text shadow lost if attributed-text is set

### ISSUE THREAD

**Issue by pcolton** [Pixate/pixate-freestyle-ios#76]
For example:

``` css
.cancelButton {
    border-radius: 3pt;
    background-color: red;
    text-shadow: 2 2 black;
}

.cancelButton attributed-text {
    letter-spacing: 2;
    color: white;
    font-size: 13;
    font-weight: 200;
}
```

The shadow is lost because it isn't being set via attributed strings.
