### ISSUE TITLE
Incorrect text-field placeholder priority

### ISSUE THREAD

**Issue by nunofgs** [Pixate/pixate-freestyle-ios#83]
Consider the following CSS:

``` css
label {
   color: red;
}

text-field placeholder {
   color: blue;
}
```

My intended result is for the textfield's placeholder to be blue, but in fact, it will be red. Since the selector 'text-field placeholder' is more specific, shouldn't it win against the 'label' selector?
