### ISSUE TITLE
Class change failing updating all styles (2.1.3 regression)

### ISSUE THREAD

**Issue by vguerci** [Pixate/pixate-freestyle-ios#99]
I style a custom checkbox, an UIButton with `button.styleId = @"filter-button";`

I toggle this checkbox using:

``` Objective-C
- (void)filter:(UIButton *)button selected:(BOOL)selected {
  button.selected = selected;
  button.styleClass = button.selected ? @"selected" : @"normal";
}
```

_(note: using this `selected` styleClass as #33 workaround)_

Styles:

``` CSS
#filter-button.selected #check-icon {
  background-image : url(icon-tick.png);
}
#filter-button.normal #check-icon {
  background-image : transparent;
}
```

The styling still works when entering the view, but is not updated properly when switching `styleClass` at `UIControlEventTouchDown`.

Calling `[button updateStyles];` after switching class fix the issue:

``` Objective-C
- (void)filter:(UIButton *)button selected:(BOOL)selected {
  button.selected = selected;
  button.styleClass = button.selected ? @"selected" : @"normal";
  [button updateStyles];
}
```
